import { randomUUID } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";

export const SCHEMA_VERSION = 7;
export const VIEWER_VERSION = "8.4.0";
export const TOKEN_ID = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
export const NODE_ID = /^(?:[a-z0-9]+(?:-[a-z0-9]+)*|[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$/;

export type JsonObject = Record<string, unknown>;
export interface IndexedProjectNode extends JsonObject { parentId?: string; depth: number }

export function assertObject(value: unknown, label: string): asserts value is JsonObject { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be an object.`); }
export function stringValue(value: unknown, label: string): string { if (typeof value !== "string") throw new Error(`${label} must be a string.`); return value; }
function isIsoDate(value: unknown): value is string { return typeof value === "string" && value.length >= 20 && !Number.isNaN(Date.parse(value)); }
export function nodes(document: JsonObject): JsonObject[] { if (!Array.isArray(document.nodes)) throw new Error("Project nodes are invalid."); return document.nodes as JsonObject[]; }
export function children(node: JsonObject): JsonObject[] { if (!Array.isArray(node.children)) throw new Error(`Node ${String(node.id)} has invalid children.`); return node.children as JsonObject[]; }
export function projectRootId(document: JsonObject): string { return stringValue((document.project as JsonObject | undefined)?.root_node_id, "project.root_node_id"); }
export function flattenNodes(entries: JsonObject[], parentId?: string, depth = 0, output: IndexedProjectNode[] = []): IndexedProjectNode[] { for (const node of entries) { output.push({ ...node, parentId, depth }); flattenNodes(children(node), stringValue(node.id, "node.id"), depth + 1, output); } return output; }
export function findNode(entries: JsonObject[], id: string): JsonObject | undefined { for (const node of entries) { if (node.id === id) return node; const nested = findNode(children(node), id); if (nested) return nested; } return undefined; }
export function projectRoot(document: JsonObject): JsonObject { const root = findNode(nodes(document), projectRootId(document)); if (!root) throw new Error("Project root node is unavailable."); return root; }

export function validateMap(value: unknown): JsonObject {
  assertObject(value, "Mind-map root"); if (value.version !== SCHEMA_VERSION) throw new Error(`Unsupported schema ${String(value.version)}; schema ${SCHEMA_VERSION} is required.`); if (typeof value.viewer_version !== "string" || !value.viewer_version.trim()) throw new Error("viewer_version must be a non-empty string.");
  assertObject(value.project, "project"); assertObject(value.llm_context, "llm_context"); assertObject(value.view, "view"); if (!Array.isArray(value.nodes)) throw new Error("nodes must be an array.");
  if (typeof value.project.root_node_id !== "string" || !NODE_ID.test(value.project.root_node_id) || Object.keys(value.project).length !== 1) throw new Error("project must contain only a valid root_node_id identity field."); if (typeof value.llm_context.summary !== "string" || !Array.isArray(value.llm_context.instructions) || value.llm_context.instructions.some((entry) => typeof entry !== "string")) throw new Error("llm_context is invalid."); assertObject(value.llm_context.tag_definitions, "llm_context.tag_definitions"); for (const [tag, description] of Object.entries(value.llm_context.tag_definitions)) if (!TOKEN_ID.test(tag) || typeof description !== "string") throw new Error(`Invalid tag definition: ${tag}`);
  if ("hidden_tags" in value.view || !Array.isArray(value.view.expanded) || (value.view.tag_filter_mode !== "include" && value.view.tag_filter_mode !== "exclude") || !Array.isArray(value.view.tag_filter_tags) || new Set(value.view.tag_filter_tags).size !== value.view.tag_filter_tags.length || value.view.tag_filter_tags.some((tag) => typeof tag !== "string" || !TOKEN_ID.test(tag))) throw new Error("view expansion or tag filters are invalid."); if (value.view.layout_mode !== undefined && value.view.layout_mode !== "hierarchy" && value.view.layout_mode !== "relations") throw new Error("view.layout_mode is invalid."); if (value.view.layout_compact !== undefined && typeof value.view.layout_compact !== "boolean") throw new Error("view.layout_compact is invalid."); if (value.view.recency_glow !== undefined && typeof value.view.recency_glow !== "boolean") throw new Error("view.recency_glow is invalid."); if (value.view.live_expand !== undefined && typeof value.view.live_expand !== "boolean") throw new Error("view.live_expand is invalid."); assertObject(value.view.positions, "view.positions"); if (typeof value.view.zoom !== "number" || !Array.isArray(value.view.viewport) || value.view.viewport.length !== 2 || value.view.viewport.some((entry) => typeof entry !== "number")) throw new Error("view geometry is invalid."); for (const [id, point] of Object.entries(value.view.positions)) if (!NODE_ID.test(id) || !Array.isArray(point) || point.length !== 2 || point.some((entry) => typeof entry !== "number")) throw new Error(`view.positions contains invalid geometry for ${id}.`); if (value.view.workspace !== undefined) assertObject(value.view.workspace, "view.workspace");
  const ids = new Set<string>(); const collected: JsonObject[] = [];
  const visit = (raw: unknown) => { assertObject(raw, "node"); if (typeof raw.id !== "string" || !NODE_ID.test(raw.id) || ids.has(raw.id)) throw new Error(`Invalid or duplicate node ID: ${String(raw.id)}`); ids.add(raw.id); collected.push(raw); for (const obsolete of ["type", "status", "categories", "date", "rationale_source"]) if (obsolete in raw) throw new Error(`Node ${raw.id} contains obsolete schema-4 field ${obsolete}.`); for (const key of ["title", "summary", "main_tag"] as const) if (typeof raw[key] !== "string") throw new Error(`Node ${raw.id}.${key} must be a string.`); if (!Array.isArray(raw.tags) || raw.tags.length === 0 || new Set(raw.tags).size !== raw.tags.length || raw.tags.some((entry) => typeof entry !== "string" || !TOKEN_ID.test(entry)) || !raw.tags.includes(raw.main_tag)) throw new Error(`Node ${raw.id} has invalid tags or main_tag.`); if (raw.rationale !== undefined && typeof raw.rationale !== "string") throw new Error(`Node ${raw.id}.rationale must be a string.`); if (!isIsoDate(raw.created_at) || !isIsoDate(raw.modified_at)) throw new Error(`Node ${raw.id} requires valid created_at and modified_at timestamps.`); if (!Array.isArray(raw.children) || !Array.isArray(raw.links)) throw new Error(`Node ${raw.id} has invalid children or links.`); raw.children.forEach(visit); };
  value.nodes.forEach(visit); if (value.nodes.length !== 1 || (value.nodes[0] as JsonObject).id !== value.project.root_node_id) throw new Error("nodes must contain exactly the designated project root node."); for (const node of collected) for (const rawLink of node.links as unknown[]) { assertObject(rawLink, `Link on ${String(node.id)}`); if (typeof rawLink.target !== "string" || !ids.has(rawLink.target) || rawLink.target === node.id || typeof rawLink.relation !== "string" || !TOKEN_ID.test(rawLink.relation)) throw new Error(`Node ${String(node.id)} has an invalid link.`); }
  for (const id of value.view.expanded as unknown[]) if (typeof id !== "string" || !ids.has(id)) throw new Error(`view.expanded contains unknown node ${String(id)}.`); if (!(value.view.expanded as unknown[]).includes(value.project.root_node_id)) throw new Error("The project root must remain expanded."); return value;
}

export function createEmptyProject(name = "Untitled project", summary = ""): JsonObject {
  const timestamp = new Date().toISOString(), id = randomUUID().toLowerCase();
  return validateMap({ version: SCHEMA_VERSION, viewer_version: VIEWER_VERSION, project: { root_node_id: id }, llm_context: { summary: "", instructions: [], tag_definitions: {} }, nodes: [{ id, title: name.trim() || "Untitled project", tags: ["concept", "project-governance"], main_tag: "project-governance", summary, created_at: timestamp, modified_at: timestamp, children: [], links: [] }], view: { expanded: [id], positions: { [id]: [600, 400] }, zoom: 0.7, viewport: [0, 0], tag_filter_mode: "exclude", tag_filter_tags: [], layout_mode: "hierarchy", layout_compact: false, recency_glow: false, live_expand: false } });
}

export function generateUniqueId(document: JsonObject): string { const ids = new Set(flattenNodes(nodes(document)).map((node) => stringValue(node.id, "node.id"))); let id = randomUUID().toLowerCase(); while (ids.has(id)) id = randomUUID().toLowerCase(); return id; }

export async function readProject(filePath: string): Promise<{ document: JsonObject; revision: string }> { const raw = await fs.readFile(filePath, "utf8"), parsed = JSON.parse(raw); return { document: validateMap(parsed), revision: JSON.stringify(parsed) }; }

export async function writeProjectAtomic(filePath: string, raw: unknown, expectedRevision?: string): Promise<JsonObject> {
  const candidate = structuredClone(raw); assertObject(candidate, "Mind-map root"); candidate.viewer_version = VIEWER_VERSION; const document = validateMap(candidate);
  if (expectedRevision !== undefined) { const current = await fs.readFile(filePath, "utf8"); if (JSON.stringify(JSON.parse(current)) !== expectedRevision) throw new Error("The project changed after it was read; reload it before saving to avoid overwriting newer changes."); }
  await fs.mkdir(path.dirname(filePath), { recursive: true }); const temporary = path.join(path.dirname(filePath), `.${path.basename(filePath)}.${process.pid}.${randomUUID()}.tmp`);
  try { await fs.writeFile(temporary, `${JSON.stringify(document, null, 2)}\n`, { encoding: "utf8", flag: "wx" }); await fs.rename(temporary, filePath); return document; } catch (error) { await fs.rm(temporary, { force: true }).catch(() => undefined); throw error; }
}

export async function createProjectFile(filePath: string, name?: string, summary?: string): Promise<JsonObject> { const document = createEmptyProject(name, summary); await fs.mkdir(path.dirname(filePath), { recursive: true }); const handle = await fs.open(filePath, "wx"); try { await handle.writeFile(`${JSON.stringify(document, null, 2)}\n`, "utf8"); } finally { await handle.close(); } return document; }

export async function mutateProject(filePath: string, mutation: (document: JsonObject) => unknown): Promise<{ document: JsonObject; result: unknown }> { const { document, revision } = await readProject(filePath); const result = mutation(document); const saved = await writeProjectAtomic(filePath, document, revision); return { document: saved, result }; }

export function normalizeTags(value: string[] | string | undefined, fallback = ["uncategorized"]): string[] { const source = value === undefined ? fallback : Array.isArray(value) ? value : value.split(","); const tags = [...new Set(source.map((tag) => tag.trim()).filter(Boolean))]; if (!tags.length || tags.some((tag) => !TOKEN_ID.test(tag))) throw new Error("Tags must be non-empty lowercase kebab-case values."); return tags; }
export function normalizeRelation(value: string): string { if (!TOKEN_ID.test(value)) throw new Error("relation must be lowercase kebab-case."); return value; }
export function touch(node: JsonObject): void { node.modified_at = new Date().toISOString(); }

export function setLlmContextSummary(document: JsonObject, summary: string): JsonObject { const context = document.llm_context as JsonObject; context.summary = summary; return context; }
export function addLlmInstruction(document: JsonObject, instruction: string): JsonObject { const context = document.llm_context as JsonObject, value = instruction.trim(); if (!value) throw new Error("instruction must not be empty."); const instructions = context.instructions as string[]; if (!instructions.includes(value)) instructions.push(value); return context; }
export function removeLlmInstruction(document: JsonObject, instruction: string): JsonObject { const context = document.llm_context as JsonObject, instructions = context.instructions as string[], index = instructions.indexOf(instruction); if (index < 0) throw new Error("The specified instruction does not exist."); instructions.splice(index, 1); return context; }
export function defineProjectTag(document: JsonObject, tag: string, description: string): JsonObject { if (!TOKEN_ID.test(tag)) throw new Error("tag must be lowercase kebab-case."); const context = document.llm_context as JsonObject, definitions = context.tag_definitions as JsonObject; definitions[tag] = description; return context; }
export function removeProjectTagDefinition(document: JsonObject, tag: string): JsonObject { if (!TOKEN_ID.test(tag)) throw new Error("tag must be lowercase kebab-case."); const context = document.llm_context as JsonObject, definitions = context.tag_definitions as JsonObject; if (!(tag in definitions)) throw new Error(`Tag definition ${tag} does not exist.`); delete definitions[tag]; return context; }

export function createProjectNode(document: JsonObject, input: { parentId?: string; title: string; summary?: string; rationale?: string; tags?: string[] | string; mainTag?: string }): JsonObject {
  const tags = normalizeTags(input.tags), mainTag = input.mainTag ?? tags[0]; if (!tags.includes(mainTag)) throw new Error("main_tag must occur in tags."); const parentId = input.parentId ?? projectRootId(document), parent = findNode(nodes(document), parentId); if (!parent) throw new Error(`Parent node ${parentId} does not exist.`); const timestamp = new Date().toISOString(); const node: JsonObject = { id: generateUniqueId(document), title: input.title.trim() || "Untitled node", tags, main_tag: mainTag, summary: input.summary ?? "", ...(input.rationale ? { rationale: input.rationale } : {}), created_at: timestamp, modified_at: timestamp, children: [], links: [] }; children(parent).push(node); touch(parent); return node;
}

export function updateProjectNode(document: JsonObject, id: string, input: { title?: string; summary?: string; rationale?: string | null; tags?: string[] | string; mainTag?: string }): JsonObject {
  const node = findNode(nodes(document), id); if (!node) throw new Error(`Node ${id} does not exist.`); if (input.title !== undefined) node.title = input.title.trim() || "Untitled node"; if (input.summary !== undefined) node.summary = input.summary; if (input.rationale === null) delete node.rationale; else if (input.rationale !== undefined) node.rationale = input.rationale; if (input.tags !== undefined) node.tags = normalizeTags(input.tags); if (input.mainTag !== undefined) node.main_tag = input.mainTag; if (!(node.tags as unknown[]).includes(node.main_tag)) throw new Error("main_tag must occur in tags."); touch(node); return node;
}

function detachNode(entries: JsonObject[], id: string): { node?: JsonObject; nodes: JsonObject[]; parent?: JsonObject } { for (let index = 0; index < entries.length; index += 1) { const entry = entries[index]; if (entry.id === id) return { node: entry, nodes: [...entries.slice(0, index), ...entries.slice(index + 1)] }; const nested = detachNode(children(entry), id); if (nested.node) { entry.children = nested.nodes; touch(entry); return { node: nested.node, nodes: entries, parent: entry }; } } return { nodes: entries }; }
export function moveProjectNode(document: JsonObject, id: string, parentId: string): JsonObject { if (id === projectRootId(document)) throw new Error("The project root cannot be moved."); if (id === parentId) throw new Error("A node cannot be its own parent."); const moving = findNode(nodes(document), id), parent = findNode(nodes(document), parentId); if (!moving) throw new Error(`Node ${id} does not exist.`); if (!parent) throw new Error(`Parent node ${parentId} does not exist.`); if (findNode(children(moving), parentId)) throw new Error("A node cannot be moved beneath its own descendant."); const detached = detachNode(nodes(document), id); if (!detached.node) throw new Error(`Node ${id} could not be detached.`); document.nodes = detached.nodes; const freshParent = findNode(nodes(document), parentId); if (!freshParent) throw new Error(`Parent node ${parentId} became unavailable.`); children(freshParent).push(detached.node); touch(freshParent); touch(detached.node); return detached.node; }

export function deleteProjectNode(document: JsonObject, id: string): number { if (id === projectRootId(document)) throw new Error("The project root cannot be deleted."); const all = flattenNodes(nodes(document)); const removed = new Set<string>(); const collect = (target: string) => { const node = all.find((entry) => entry.id === target); if (!node) throw new Error(`Node ${target} does not exist.`); removed.add(target); for (const child of all) if (child.parentId === target) collect(stringValue(child.id, "node.id")); }; collect(id); const clean = (entries: JsonObject[]): JsonObject[] => entries.filter((node) => !removed.has(stringValue(node.id, "node.id"))).map((node) => { const nextChildren = clean(children(node)), links = node.links as unknown[]; const nextLinks = links.filter((raw) => { assertObject(raw, "link"); return !removed.has(stringValue(raw.target, "link.target")); }); if (nextChildren.length !== children(node).length || nextLinks.length !== links.length) touch(node); node.children = nextChildren; node.links = nextLinks; return node; }); document.nodes = clean(nodes(document)); const view = document.view as JsonObject; view.expanded = (view.expanded as unknown[]).filter((entry) => !removed.has(String(entry))); const positions = view.positions as JsonObject; for (const removedId of removed) delete positions[removedId]; return removed.size; }

export function changeProjectLink(document: JsonObject, action: "add" | "remove", sourceId: string, targetId: string, relationValue: string): JsonObject { const source = findNode(nodes(document), sourceId), target = findNode(nodes(document), targetId); if (!source || !target || sourceId === targetId) throw new Error("Link endpoints are invalid."); const relation = normalizeRelation(relationValue), links = source.links as Array<{ target: string; relation: string }>; if (action === "add" && !links.some((link) => link.target === targetId && link.relation === relation)) links.push({ target: targetId, relation }); if (action === "remove") source.links = links.filter((link) => link.target !== targetId || link.relation !== relation); touch(source); return source;
}
