import { useEffect, useRef, useState } from "react";

type Mode = "draft" | "edit" | "full";
type Provider = "openai" | "fhgenie";
type Message = { role: "user" | "assistant"; content: string };
type Approval = { id: string; requiredMode: "edit" | "full"; reason: string };
const FHGENIE_MODELS = ["nvidia/GLM-5.2-NVFP4", "deepseek-ai/DeepSeek-V4-Flash-0731", "openGPT-X/Teuken-7B-instruct-v0.6", "MiniMaxAI/MiniMax-M2.5", "Qwen/Qwen3-Coder-Next-FP8"];
const modeHelp: Record<Mode, string> = {
  draft: "Chat and plan only. The project cannot be changed.",
  edit: "May create and edit nodes and links, but cannot delete.",
  full: "May create, edit, link, and permanently delete nodes.",
};

export function AssistantPanel() {
  const [provider, setProvider] = useState<Provider>("openai"); const [hasKey, setHasKey] = useState(false); const [apiKey, setApiKey] = useState(""); const [models, setModels] = useState<string[]>([]); const [model, setModel] = useState(""); const [mode, setMode] = useState<Mode>("draft"); const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(""); const [approval, setApproval] = useState<Approval>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const end = useRef<HTMLDivElement>(null);
  const providerName = provider === "fhgenie" ? "FhGenie" : "OpenAI"; const availableModels = [...new Set([...(provider === "fhgenie" ? FHGENIE_MODELS : []), ...models])];
  useEffect(() => { void window.mindmap.assistant.status().then((status) => { setProvider(status.provider); setHasKey(status.hasKey); setModel(status.model); }).catch((reason) => setError(String(reason))); }, []);
  useEffect(() => { end.current?.scrollIntoView({ block: "end" }); }, [messages, approval, busy]);
  const refreshModels = async () => { setBusy(true); setError(""); try { setModels(await window.mindmap.assistant.models(provider)); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } };
  const chooseProvider = async (value: Provider) => { setBusy(true); setError(""); try { const status = await window.mindmap.assistant.setProvider(value); setProvider(status.provider); setHasKey(status.hasKey); setModel(status.model); setModels([]); setApiKey(""); setApproval(undefined); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } };
  const saveKey = async () => { setBusy(true); setError(""); try { const status = await window.mindmap.assistant.saveKey(provider, apiKey); setApiKey(""); setHasKey(status.hasKey); setModels(await window.mindmap.assistant.models(provider)); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } };
  const deleteKey = async () => { if (!confirm(`Delete the securely stored ${providerName} API key from this computer?`)) return; setBusy(true); setError(""); try { const status = await window.mindmap.assistant.deleteKey(provider); setHasKey(status.hasKey); setModels([]); setApproval(undefined); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } };
  const chooseModel = async (value: string) => { setModel(value); setError(""); try { await window.mindmap.assistant.setModel(provider, value); } catch (reason) { setError(String(reason)); } };
  const newChat = async () => { if (busy) return; if ((messages.length > 0 || input.trim()) && !confirm("Delete the current chat and start with a fresh context?")) return; setError(""); try { await window.mindmap.assistant.newChat(); setMessages([]); setInput(""); setApproval(undefined); } catch (reason) { setError(String(reason)); } };
  const appendReply = (reply: { text: string; approval?: Approval }) => { setMessages((current) => [...current, { role: "assistant", content: reply.text }]); setApproval(reply.approval); };
  const submit = async () => { const text = input.trim(); if (!text || busy) return; if (!hasKey) { setError(`Save a ${providerName} API key before sending.`); return; } if (!model) { setError("Choose a model before sending."); return; } const outgoing = [...messages, { role: "user" as const, content: text }]; setMessages(outgoing); setInput(""); setApproval(undefined); setBusy(true); setError(""); try { appendReply(await window.mindmap.assistant.chat(outgoing, mode)); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } };
  const resolveApproval = async (accepted: boolean) => { if (!approval || busy) return; const pending = approval; setApproval(undefined); setBusy(true); setError(""); setMessages((current) => [...current, { role: "user", content: accepted ? `Approved ${pending.requiredMode} permission for this task.` : "Permission declined." }]); try { appendReply(await window.mindmap.assistant.resolveApproval(pending.id, accepted)); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } };
  return <section className="assistant-panel">
    <header><div><p className="eyebrow">AI ASSISTANT</p><strong>{providerName} · project scoped</strong></div><div className="assistant-header-actions"><button onClick={() => void newChat()} disabled={busy}>New chat</button><div className={`assistant-connection ${hasKey ? "ready" : ""}`}>{hasKey ? "Key saved" : "No API key"}</div></div></header>
    <div className="assistant-settings">
      <div className="assistant-model-row"><label>Provider<select value={provider} disabled={busy || Boolean(approval)} onChange={(event) => void chooseProvider(event.target.value as Provider)}><option value="openai">OpenAI</option><option value="fhgenie">FhGenie</option></select></label></div>
      {!hasKey ? <div className="assistant-key-row"><input type="password" autoComplete="off" placeholder={`${providerName} API key`} value={apiKey} onChange={(event) => setApiKey(event.target.value)} /><button onClick={() => void saveKey()} disabled={busy || !apiKey.trim()}>Save securely</button></div> : <div className="assistant-key-row"><span>The {providerName} key is encrypted with the operating-system credential service.</span><button className="danger" onClick={() => void deleteKey()} disabled={busy}>Delete API key</button></div>}
      <div className="assistant-model-row"><label>Model<select value={model} disabled={!hasKey || busy} onChange={(event) => void chooseModel(event.target.value)}><option value="">Choose a model</option>{model && !availableModels.includes(model) && <option value={model}>{model}</option>}{availableModels.map((entry) => <option value={entry} key={entry}>{entry}</option>)}</select></label><button onClick={() => void refreshModels()} disabled={!hasKey || busy}>Refresh models</button></div>
      <div className="assistant-modes" role="group" aria-label="Assistant permission mode">{(["draft", "edit", "full"] as Mode[]).map((entry) => <button key={entry} className={mode === entry ? "active" : ""} disabled={busy || Boolean(approval)} onClick={() => setMode(entry)} title={modeHelp[entry]}>{entry}</button>)}</div><p className="assistant-mode-help">{modeHelp[mode]}</p>
    </div>
    <div className="assistant-chat">{messages.length === 0 && <div className="assistant-empty"><strong>Work with the current knowledge map</strong><p>The assistant follows the project’s AGENTS.md and can access only the currently open mindmap.json.</p></div>}{messages.map((message, index) => <article className={`assistant-message ${message.role}`} key={index}><span>{message.role === "user" ? "You" : "Assistant"}</span><p>{message.content}</p></article>)}{approval && <aside className="assistant-approval"><strong>Permission required: {approval.requiredMode}</strong><p>{approval.reason}</p><div><button onClick={() => void resolveApproval(false)} disabled={busy}>Decline</button><button className="primary" onClick={() => void resolveApproval(true)} disabled={busy}>Accept once</button></div></aside>}{busy && <div className="assistant-thinking">Working…</div>}<div ref={end} /></div>
    {error && <div className="assistant-error">{error}</div>}
    <footer><textarea placeholder={!hasKey ? "Write a message, then configure an API key above…" : !model ? "Write a message, then choose a model above…" : "Ask about or work on the current project…"} value={input} disabled={Boolean(approval)} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && (event.ctrlKey || event.metaKey)) { event.preventDefault(); void submit(); } }} /><button className="primary" onClick={() => void submit()} disabled={!hasKey || !model || !input.trim() || busy || Boolean(approval)}>Send</button></footer>
  </section>;
}
